export enum ErrorCode {
  VALIDATION_ERROR = 'VALIDATION_ERROR',
  REPORT_DATE_REQUIRED = 'REPORT_DATE_REQUIRED',
  REPORT_NAME_ALREADY_EXISTS = 'REPORT_NAME_ALREADY_EXISTS',
  REPORT_NOT_FOUND = 'REPORT_NOT_FOUND',
  REPORT_ALREADY_RUNNING = 'REPORT_ALREADY_RUNNING',
  REPORT_SUMMARY_NOT_FOUND = 'REPORT_SUMMARY_NOT_FOUND',
  REPORT_AGGREGATION_FAILED = 'REPORT_AGGREGATION_FAILED',
  INTERNAL_ERROR = 'INTERNAL_ERROR',
}
